$path = "C:\Users\luxan\.gemini\antigravity\scratch\kitchen-erp\pedido.html"
$content = [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8)

# Substituições diretas de strings conhecidas corrompidas
$content = $content.Replace("Inventǭrio", "Inventário")
$content = $content.Replace("vocǦ", "você")
$content = $content.Replace("Qual Ǹ", "Qual é")
$content = $content.Replace("Inclusǜo", "Inclusão")
$content = $content.Replace("Reposiǜo", "Reposição")
$content = $content.Replace("Mǭximo", "Máximo")
$content = $content.Replace("Mǭx", "Máx")
$content = $content.Replace("necessǭrio", "necessário")
$content = $content.Replace("Catǭlogo", "Catálogo")
$content = $content.Replace("indisponvel", "indisponível")
$content = $content.Replace("nǜo", "não")
$content = $content.Replace("PrǸ", "Pré")
$content = $content.Replace("ndice", "índice")
$content = $content.Replace("alfabǸtica", "alfabética")
$content = $content.Replace("hǭ", "há")
$content = $content.Replace("jǭ", "já")
$content = $content.Replace("atǸ", "até")
$content = $content.Replace("Qual Ǹ a sua loja?", "Qual é a sua loja?")
$content = $content.Replace("ITAPOǟ", "ITAPOÃ")
$content = $content.Replace("Aucar", "Açúcar")
$content = $content.Replace("CafǸ", "Café")
$content = $content.Replace("moda", "moída")
$content = $content.Replace("FilǸ", "Filé")
$content = $content.Replace("Pea", "Peça")
$content = $content.Replace("Galǜo", "Galão")
$content = $content.Replace("Sabǜo", "Sabão")
$content = $content.Replace("Lanamento", "Lançamento")
$content = $content.Replace("separaǜo", "separação")

[IO.File]::WriteAllText($path, $content, [Text.Encoding]::UTF8)
Write-Host "Pedido.html corrigido."
